homepage: https://openwrt.org/docs/techref/ustp
language: c
primary_contact: steven@midlink.org
auto_ccs:
  - dedeckeh@gmail.com
main_repo: https://github.com/Dudcom/ustp-oss-fuzz.git
sanitizers:
  - address
architectures:
  - x86_64
  - i386 
